### ISSUE TITLE
[COMPAT] Add compatibility for jobsreborn

### ISSUE THREAD

**Issue by Tizooo** [SourceWriters/SmoothTimber#30]
**What version and plugin do you want us to add compatibility for?**

jobs reborn

**Why should we add compatibility for this plugin with that version?**
so if trees are broken the timber job gets money for it

**Comment by Lauriichan** [comment]
Please fill out the full template instead of removing parts of it.

Right now I'm unable to help you as we already have JobsReborn support and I can't find out what is wrong on your side.
If you either didn't configure the JobsReborn support or if you have a unsupported version installed.

Please either message us on discord to resolve your issue or create a new help issue which contains all required information as well as the Plugin version and Plugin name which u are facing a problem with.
https://github.com/SourceWriters/SmoothTimber/blob/legacy/.github/ISSUE_TEMPLATE/help-request-or-question.md
