### ISSUE TITLE
[BUG] BlockyLog disables use of /sm toggle

### ISSUE THREAD

**Issue by VirtualJunky** [SourceWriters/SmoothTimber#32]
**Describe the bug**
Been using this plugin for a while now but my community finally got fed up with it destroying their houses when trying to remove 1 block and asked for a solution. I went with the first option listed on the resource page, being BlockyLog, and people who previously had toggled off SmoothTimber with the /SM Toggle could no longer use the command to enable it again. Even myself being an OP could not run the command anymore. We don't use any permission base scripts and don't really care to either since its just a small tight nit community run server, so perhaps with real permissions setup it wouldn't be an issue.

**To Reproduce**
1. Install BlockyLog
2. Attempt to use /sm toggle
3. "You do not have permission to use this command"

**Server:**
 - Software: Paper
 - Server Version: 1.18.1
 - Plugin Version: 1.18.3
 - Java Version: Unknown, hosted server and doesn't clarify even in their knowledge base.

**Additional context**
Swapped to CoreProtect and it seems to work perfectly. Server is absolute bare bones, having only SmoothTimber, ClickSort, SavageDeathChest, VillagerSaver and now CoreProtect. 

I also tried setting the config option "toggleable" to true, which didn't help. Unsure what that setting even does as the wiki says "Toggles the toggleable functionality" which isn't very helpful or clear, but had assumed it was the /sm toggle command.

Also as a side note, only mentioning it because its sort of related. On the main page it recommends BlockyLog or CoreProtect, but everywhere else, such as the wiki and even messages in the Discord all mention LogBlock or CoreProtect which is slightly confusing when trying to find a solution.

Hopefully this all helps in some way, and thanks for an awesome plugin.

**Comment by Lauriichan** [comment]
First of all I don't think that this is a bug of SmoothTimber as the permission message of SmoothTimber is actually different as SmoothTimber is handling the permissions internally and not using bukkit therefore it was probably another plugin which either overwrote the command or something else.
And even if it can't be a bug of SmoothTimber as SmoothTimber uses the permission system of the bukkit api so if the permission isn't set anymore or something it is related to another plugin and not SmoothTimber itself.

About the third party plugin recommendation: BlockyLog is a bit buggy and is no longer maintained by us as we don't see the reason to still maintain it. We were not able to create a fast and stable player logging plugin which doesn't lose data while still being well fast. Therefore we recommend using LogBlock and mention that it is able to use CoreProtect or BlockyLog

And last thing about the 'toggleable' function on the wiki yeah the description can be a bit unclear if you don't look at the config values for it. The setting is to specify how the "toggleable" functionality should behave or if it should be disabled.
Same thing with the "sneak" setting but instead of a command it is for sneaking.

**Comment by Lauriichan** [comment]
Oh about the permission there is actually one case where it does send the Bukkit permission message, which is when not having the "smoothtimber.use" permission. "smoothtimber.use" should be granted by default.
If you reloaded the server then that could actually be the problem.

EDIT: I think I will change that in the next release

**Comment by VirtualJunky** [comment]
Yeah when I first installed BlockyLog I used /reload as a quick test and got the error message, figured it might be an issue of using the /reload command so did a full restart and had the same result. Removed BlockyLog and used just /reload and instantly could use /sm toggle again. So I figured it was some weird conflict and didn't really know which plugin caused it, but since it was the first recommended plugin for this plugin I figured I'd make a report here since at the very least it could be fixed in this plugin if possible or at least be useful in some way.
